### 查询服务
GET http://127.0.0.1:9001/pinc/pinc-commerce-nacos-client/nacos-client/service-instance?serviceId=pinc-commerce-gateway
Accept: application/json
pinc-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJwaW5jLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEzLFwidXNlcm5hbWVcIjpcInpoYW9saXVcIn0iLCJleHAiOjE2MzY5OTIwMDAsImp0aSI6IjExODE3NDllLTczNDctNDVjOC04NWM3LTkwNTUyZjViOTcyOCJ9.VL_yE7ieEExqE0_jYDMqPwHnapCl4QrjxExUiANBCvVtqIPxOxZtPslNFKApXsU_TeSg42M6oJMMvOlehpEPXe_yN3r_1_RkQcwknpJhKLQ-eQgMgiwzYDOMVDGt0TnJ1aUll1xHZQWPLiJd4UvWvm4cBbPvZbaBy8URRcvU0uZIGjjxibzw-tjU2Yt-iXMoy6wX9YKOaf_AMqIEIJVeTlihNAim5DkEZ6qGyHPKC29BAIwDXOIPZoLgq2Ct1IVJN41oi68-t6zN4XcsFPKaCyrxUP23DMaOfy5e-x4Z4wcNGEREL7GULQF7Iz4ZFsDiIOaM9CnIfLJ1HnR-GCggoQ

